default_platform(:ios)

def pod_repo_sources()
  ["git@github.com:intergi/playwire-ios-podspec.git", "https://github.com/CocoaPods/Specs"]
end

def podspec_file()
  "Playwire.podspec"
end

def pod_repo_name()
  "plw-ios-podspec"
end

lane :lint_pod do
  pod_lib_lint(
    podspec:podspec_file,
    sources:pod_repo_sources,
    verbose: true,
    allow_warnings: true,
    use_libraries: true,
    skip_tests: true,
    no_subspecs: true
  )
end

lane :push_pod do
  pod_push(
    path:podspec_file,
    sources: pod_repo_sources,
    repo: pod_repo_name,
    verbose: true,
    allow_warnings: true,
    use_libraries: true,
    skip_tests: true,
    skip_import_validation: true
  )
end