// Generated by Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)
#ifndef PLAYWIRE_SWIFT_H
#define PLAYWIRE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import GoogleMobileAds;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Playwire",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif




SWIFT_CLASS("_TtC8Playwire10PWAdBidder")
@interface PWAdBidder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PWAdMediatorConfig;
@class NSNumber;
@class GADRequest;

SWIFT_PROTOCOL("_TtP8Playwire12PWAdMediator_")
@protocol PWAdMediator
@property (nonatomic, strong) PWAdMediatorConfig * _Nullable config;
- (nonnull instancetype)init;
- (void)setup;
- (void)enableGDPR:(BOOL)enabled;
- (void)configureWithRequest:(GADRequest * _Nonnull)request;
@end

@class NSString;

SWIFT_CLASS("_TtC8Playwire18PWAdMediatorConfig")
@interface PWAdMediatorConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdMediatorType_AdColony;)
+ (NSString * _Nonnull)PWAdMediatorType_AdColony SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdMediatorType_Vungle;)
+ (NSString * _Nonnull)PWAdMediatorType_Vungle SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdMediatorType_Smaato;)
+ (NSString * _Nonnull)PWAdMediatorType_Smaato SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nullable adcolony_appId;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable adcolony_zones;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable vungle_placements;
@property (nonatomic, readonly, copy) NSString * _Nullable vungle_userId;
@property (nonatomic, readonly, copy) NSString * _Nullable smaato_publisherId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface PWAdMediatorConfig (SWIFT_EXTENSION(Playwire))
@property (nonatomic, readonly, strong) NSNumber * _Nullable adcolony_shouldShowPrePopup;
@property (nonatomic, readonly, strong) NSNumber * _Nullable adcolony_shouldShowPostPopup;
@property (nonatomic, readonly, strong) NSNumber * _Nullable vungle_shouldStartMuted;
@end


SWIFT_PROTOCOL("_TtP8Playwire22PWAdNetworkRegistrable_")
@protocol PWAdNetworkRegistrable
+ (void)register;
@end


SWIFT_CLASS("_TtC8Playwire16PWAdServerConfig")
@interface PWAdServerConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdServerType_Amazon;)
+ (NSString * _Nonnull)PWAdServerType_Amazon SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdServerType_Prebid;)
+ (NSString * _Nonnull)PWAdServerType_Prebid SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nullable host;
@property (nonatomic, readonly, copy) NSString * _Nullable account;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8Playwire8PWAdSize")
@interface PWAdSize : NSObject
@property (nonatomic, readonly) NSInteger width;
@property (nonatomic, readonly) NSInteger height;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PWAdUnitConfig;
@class PWBannerRefresh;

SWIFT_CLASS("_TtC8Playwire8PWAdUnit")
@interface PWAdUnit : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdBidStrategyType_Priority;)
+ (NSString * _Nonnull)PWAdBidStrategyType_Priority SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdBidStrategyType_Combined;)
+ (NSString * _Nonnull)PWAdBidStrategyType_Combined SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdMode_Banner;)
+ (NSString * _Nonnull)PWAdMode_Banner SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdMode_Interstitial;)
+ (NSString * _Nonnull)PWAdMode_Interstitial SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdMode_Rewarded;)
+ (NSString * _Nonnull)PWAdMode_Rewarded SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdMode_AppOpenAd;)
+ (NSString * _Nonnull)PWAdMode_AppOpenAd SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdMode_RewardedInterstitial;)
+ (NSString * _Nonnull)PWAdMode_RewardedInterstitial SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSArray<PWAdUnitConfig *> * _Nullable adUnitConfigs;
@property (nonatomic, readonly, strong) PWBannerRefresh * _Nullable refresh;
@property (nonatomic, readonly, copy) NSString * _Nonnull gadUnitId;
@property (nonatomic, readonly, copy) NSArray<PWAdSize *> * _Nullable gadSizes;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable customTargets;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8Playwire14PWAdUnitConfig")
@interface PWAdUnitConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull serverConfig;
@property (nonatomic, readonly, copy) NSString * _Nonnull adUnitId;
@property (nonatomic, readonly, copy) NSArray<PWAdSize *> * _Nullable adSizes;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PWUMPConfig;
@class PWAppConfig;
@class PWOMConfig;
@class PWSchainConfig;

SWIFT_CLASS("_TtC8Playwire19PWAdUnitStoreConfig")
@interface PWAdUnitStoreConfig : NSObject
@property (nonatomic, readonly, copy) NSArray<PWAdServerConfig *> * _Nullable serverConfigs;
@property (nonatomic, readonly, copy) NSArray<PWAdUnit *> * _Nonnull adUnits;
@property (nonatomic, readonly, copy) NSArray<PWAdMediatorConfig *> * _Nullable mediators;
@property (nonatomic, readonly, strong) PWUMPConfig * _Nullable ump;
@property (nonatomic, readonly, strong) PWAppConfig * _Nullable app;
@property (nonatomic, readonly, strong) PWOMConfig * _Nullable om;
@property (nonatomic, readonly, strong) PWSchainConfig * _Nullable schain;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8Playwire11PWAppConfig")
@interface PWAppConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable gamAppId;
@property (nonatomic, readonly, copy) NSString * _Nullable storeUrl;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol PWFullScreenAdDelegate;
@class UIViewController;

SWIFT_CLASS("_TtC8Playwire14PWFullScreenAd")
@interface PWFullScreenAd : NSObject
@property (nonatomic, readonly, strong) PWAdUnit * _Nullable adUnit;
@property (nonatomic, readonly) BOOL isLoaded;
@property (nonatomic, weak) id <PWFullScreenAdDelegate> _Nullable delegate;
- (void)load;
- (void)loadWithCustomTargets:(NSDictionary<NSString *, NSString *> * _Nullable)customTargets;
- (void)showFromViewController:(UIViewController * _Nonnull)viewController;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8Playwire11PWAppOpenAd")
@interface PWAppOpenAd : PWFullScreenAd
@property (nonatomic) BOOL autoReloadOnExpiration;
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName delegate:(id <PWFullScreenAdDelegate> _Nullable)delegate;
- (void)load;
- (void)loadWithCustomTargets:(NSDictionary<NSString *, NSString *> * _Nullable)customTargets;
- (void)loadWithOrientation:(UIInterfaceOrientation)orientation;
- (void)loadWithOrientation:(UIInterfaceOrientation)orientation customTargets:(NSDictionary<NSString *, NSString *> * _Nullable)customTargets;
- (void)showFromViewController:(UIViewController * _Nonnull)viewController;
@end



SWIFT_CLASS("_TtC8Playwire15PWBannerRefresh")
@interface PWBannerRefresh : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol PWViewAdDelegate;
@class NSCoder;

SWIFT_CLASS("_TtC8Playwire8PWViewAd")
@interface PWViewAd : UIView
@property (nonatomic, copy) NSString * _Nullable adUnitName;
@property (nonatomic) BOOL autoload;
@property (nonatomic, readonly, strong) PWAdUnit * _Nullable adUnit;
@property (nonatomic, weak) id <PWViewAdDelegate> _Nullable delegate;
@property (nonatomic, weak) UIViewController * _Nullable viewController;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName controller:(UIViewController * _Nullable)controller delegate:(id <PWViewAdDelegate> _Nullable)delegate;
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName delegate:(id <PWViewAdDelegate> _Nullable)delegate;
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName controller:(UIViewController * _Nullable)controller;
- (void)awakeFromNib;
- (void)load;
- (void)loadWithCustomTargets:(NSDictionary<NSString *, NSString *> * _Nullable)customTargets;
@property (nonatomic, readonly) BOOL isLoaded;
- (void)refresh;
@end


SWIFT_CLASS("_TtC8Playwire12PWBannerView")
@interface PWBannerView : PWViewAd
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class GADBannerView;

@interface PWBannerView (SWIFT_EXTENSION(Playwire)) <GADAdSizeDelegate>
- (void)adView:(GADBannerView * _Nonnull)bannerView willChangeAdSizeTo:(GADAdSize)size;
@end


@interface PWBannerView (SWIFT_EXTENSION(Playwire)) <GADBannerViewDelegate>
- (void)bannerViewDidReceiveAd:(GADBannerView * _Nonnull)bannerView;
- (void)bannerView:(GADBannerView * _Nonnull)bannerView didFailToReceiveAdWithError:(NSError * _Nonnull)error;
- (void)bannerViewDidRecordImpression:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewDidRecordClick:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewWillPresentScreen:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewWillDismissScreen:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewDidDismissScreen:(GADBannerView * _Nonnull)bannerView;
@end


SWIFT_CLASS("_TtC8Playwire3PWC")
@interface PWC : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull Version;)
+ (NSString * _Nonnull)Version SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamInit;)
+ (NSString * _Nonnull)EVT_gamInit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamInit_status;)
+ (NSString * _Nonnull)EVT_gamInit_status SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_ump;)
+ (NSString * _Nonnull)EVT_ump SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_ump_result;)
+ (NSString * _Nonnull)EVT_ump_result SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_bidding_index;)
+ (NSString * _Nonnull)EVT_CTX_bidding_index SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_bidding_adUnit;)
+ (NSString * _Nonnull)EVT_CTX_bidding_adUnit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_biddingStart;)
+ (NSString * _Nonnull)EVT_biddingStart SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_biddingStart_timestamp;)
+ (NSString * _Nonnull)EVT_biddingStart_timestamp SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_biddingEnd;)
+ (NSString * _Nonnull)EVT_biddingEnd SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_biddingEnd_timestamp;)
+ (NSString * _Nonnull)EVT_biddingEnd_timestamp SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_biddingEnd_duration;)
+ (NSString * _Nonnull)EVT_biddingEnd_duration SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_adUnit_mode;)
+ (NSString * _Nonnull)EVT_CTX_adUnit_mode SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_adUnit_name;)
+ (NSString * _Nonnull)EVT_CTX_adUnit_name SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_adUnit_gadUnitId;)
+ (NSString * _Nonnull)EVT_CTX_adUnit_gadUnitId SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_requestTimestamp;)
+ (NSString * _Nonnull)EVT_CTX_requestTimestamp SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_staticTargeting;)
+ (NSString * _Nonnull)EVT_CTX_staticTargeting SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_dynamicTargeting;)
+ (NSString * _Nonnull)EVT_CTX_dynamicTargeting SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestSuccess;)
+ (NSString * _Nonnull)EVT_gamRequestSuccess SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestSuccess_response;)
+ (NSString * _Nonnull)EVT_gamRequestSuccess_response SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestSuccess_timestamp;)
+ (NSString * _Nonnull)EVT_gamRequestSuccess_timestamp SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestSuccess_duration;)
+ (NSString * _Nonnull)EVT_gamRequestSuccess_duration SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestFail;)
+ (NSString * _Nonnull)EVT_gamRequestFail SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestFail_error;)
+ (NSString * _Nonnull)EVT_gamRequestFail_error SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestFail_timestamp;)
+ (NSString * _Nonnull)EVT_gamRequestFail_timestamp SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestFail_duration;)
+ (NSString * _Nonnull)EVT_gamRequestFail_duration SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamImpression;)
+ (NSString * _Nonnull)EVT_gamImpression SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamImpression_timestamp;)
+ (NSString * _Nonnull)EVT_gamImpression_timestamp SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_configType;)
+ (NSString * _Nonnull)EVT_CTX_configType SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_configType_Backend;)
+ (NSString * _Nonnull)EVT_CTX_configType_Backend SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_configType_Cache;)
+ (NSString * _Nonnull)EVT_CTX_configType_Cache SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_configSuccess;)
+ (NSString * _Nonnull)EVT_configSuccess SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_configSuccess_config;)
+ (NSString * _Nonnull)EVT_configSuccess_config SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_configFail;)
+ (NSString * _Nonnull)EVT_configFail SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_configFail_config;)
+ (NSString * _Nonnull)EVT_configFail_config SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_configFail_error;)
+ (NSString * _Nonnull)EVT_configFail_error SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_configFail_error_empty_file;)
+ (NSString * _Nonnull)EVT_configFail_error_empty_file SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_configFail_error_request_building;)
+ (NSString * _Nonnull)EVT_configFail_error_request_building SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_configFileLoading;)
+ (NSString * _Nonnull)EVT_configFileLoading SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_configFileLoading_status_code;)
+ (NSString * _Nonnull)EVT_configFileLoading_status_code SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_cachedConfigFileSavingFail;)
+ (NSString * _Nonnull)EVT_cachedConfigFileSavingFail SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_cachedConfigFileFail_error;)
+ (NSString * _Nonnull)EVT_cachedConfigFileFail_error SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_cachedConfigFileSavingSuccess;)
+ (NSString * _Nonnull)EVT_cachedConfigFileSavingSuccess SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adInitError;)
+ (NSString * _Nonnull)EVT_adInitError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adInitError_error;)
+ (NSString * _Nonnull)EVT_adInitError_error SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adInitError_error_alreadyInitialized;)
+ (NSString * _Nonnull)EVT_adInitError_error_alreadyInitialized SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adInitError_error_noAdUnitName;)
+ (NSString * _Nonnull)EVT_adInitError_error_noAdUnitName SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adInitError_error_noAdUnit;)
+ (NSString * _Nonnull)EVT_adInitError_error_noAdUnit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adInitError_error_badAdUnit;)
+ (NSString * _Nonnull)EVT_adInitError_error_badAdUnit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adInitError_error_badAdUnit_modeRequired;)
+ (NSString * _Nonnull)EVT_adInitError_error_badAdUnit_modeRequired SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adInitError_error_badAdUnit_modeConfig;)
+ (NSString * _Nonnull)EVT_adInitError_error_badAdUnit_modeConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adInitError_error_noSizes;)
+ (NSString * _Nonnull)EVT_adInitError_error_noSizes SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adLoadError;)
+ (NSString * _Nonnull)EVT_adLoadError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adLoadError_error;)
+ (NSString * _Nonnull)EVT_adLoadError_error SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adLoadError_error_notPrepared;)
+ (NSString * _Nonnull)EVT_adLoadError_error_notPrepared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adLoadError_error_notInternalRep;)
+ (NSString * _Nonnull)EVT_adLoadError_error_notInternalRep SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adLoadError_error_notLoaded;)
+ (NSString * _Nonnull)EVT_adLoadError_error_notLoaded SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adRefreshError;)
+ (NSString * _Nonnull)EVT_adRefreshError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adRefreshError_error;)
+ (NSString * _Nonnull)EVT_adRefreshError_error SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adRefreshError_error_maxReached;)
+ (NSString * _Nonnull)EVT_adRefreshError_error_maxReached SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adRefreshError_error_maxReached_count;)
+ (NSString * _Nonnull)EVT_adRefreshError_error_maxReached_count SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adRefreshError_error_early;)
+ (NSString * _Nonnull)EVT_adRefreshError_error_early SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adRefreshError_error_early_elapsed;)
+ (NSString * _Nonnull)EVT_adRefreshError_error_early_elapsed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adRefreshError_error_early_required;)
+ (NSString * _Nonnull)EVT_adRefreshError_error_early_required SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adRefreshError_error_manual;)
+ (NSString * _Nonnull)EVT_adRefreshError_error_manual SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adRefreshEarly;)
+ (NSString * _Nonnull)EVT_adRefreshEarly SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adReward;)
+ (NSString * _Nonnull)EVT_adReward SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adReward_type;)
+ (NSString * _Nonnull)EVT_adReward_type SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adReward_amount;)
+ (NSString * _Nonnull)EVT_adReward_amount SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adLoadWarning;)
+ (NSString * _Nonnull)EVT_adLoadWarning SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adLoadWarning_warning;)
+ (NSString * _Nonnull)EVT_adLoadWarning_warning SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adLoadWarning_warning_notProfitable;)
+ (NSString * _Nonnull)EVT_adLoadWarning_warning_notProfitable SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_adLoadWarning_autoReload;)
+ (NSString * _Nonnull)EVT_adLoadWarning_autoReload SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@protocol GADFullScreenPresentingAd;

@interface PWFullScreenAd (SWIFT_EXTENSION(Playwire)) <GADFullScreenContentDelegate>
- (void)adWillPresentFullScreenContent:(id <GADFullScreenPresentingAd> _Nonnull)ad;
- (void)adWillDismissFullScreenContent:(id <GADFullScreenPresentingAd> _Nonnull)ad;
- (void)adDidDismissFullScreenContent:(id <GADFullScreenPresentingAd> _Nonnull)ad;
- (void)ad:(id <GADFullScreenPresentingAd> _Nonnull)ad didFailToPresentFullScreenContentWithError:(NSError * _Nonnull)error;
- (void)adDidRecordImpression:(id <GADFullScreenPresentingAd> _Nonnull)ad;
- (void)adDidRecordClick:(id <GADFullScreenPresentingAd> _Nonnull)ad;
@end



SWIFT_PROTOCOL("_TtP8Playwire22PWFullScreenAdDelegate_")
@protocol PWFullScreenAdDelegate
- (void)fullScreenAdDidLoad:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidFailToLoad:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdWillPresentFullScreenContent:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdWillDismissFullScreenContent:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidDismissFullScreenContent:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidFailToPresentFullScreenContent:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidRecordImpression:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidRecordClick:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidUserEarn:(PWFullScreenAd * _Nonnull)ad type:(NSString * _Nonnull)type amount:(double)amount;
@end


SWIFT_CLASS("_TtC8Playwire14PWInterstitial")
@interface PWInterstitial : PWFullScreenAd
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName delegate:(id <PWFullScreenAdDelegate> _Nullable)delegate;
- (void)showFromViewController:(UIViewController * _Nonnull)viewController;
@end


SWIFT_CLASS("_TtC8Playwire15PWListenerToken")
@interface PWListenerToken : NSObject
- (void)cancel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol PWNativeViewFactory;

SWIFT_CLASS("_TtC8Playwire12PWNativeView")
@interface PWNativeView : PWViewAd
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName controller:(UIViewController * _Nullable)controller factory:(id <PWNativeViewFactory> _Nonnull)factory delegate:(id <PWViewAdDelegate> _Nullable)delegate OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class GADAdLoader;
@class GADNativeAd;

@interface PWNativeView (SWIFT_EXTENSION(Playwire)) <GADNativeAdLoaderDelegate>
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didReceiveNativeAd:(GADNativeAd * _Nonnull)nativeAd;
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didFailToReceiveAdWithError:(NSError * _Nonnull)error;
@end


@interface PWNativeView (SWIFT_EXTENSION(Playwire)) <GADNativeAdDelegate>
- (void)nativeAdDidRecordImpression:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdDidRecordClick:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdWillPresentScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdWillDismissScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdDidDismissScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdIsMuted:(GADNativeAd * _Nonnull)nativeAd;
@end

@class UIImage;
@class NSDecimalNumber;

SWIFT_CLASS("_TtC8Playwire19PWNativeViewContent")
@interface PWNativeViewContent : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable headline;
@property (nonatomic, readonly, copy) NSString * _Nullable body;
@property (nonatomic, readonly, copy) NSString * _Nullable callToAction;
@property (nonatomic, readonly, strong) UIImage * _Nullable icon;
@property (nonatomic, readonly, strong) UIImage * _Nullable image;
@property (nonatomic, readonly, strong) UIView * _Nullable mediaView;
@property (nonatomic, readonly, strong) NSDecimalNumber * _Nullable starRating;
@property (nonatomic, readonly, copy) NSString * _Nullable store;
@property (nonatomic, readonly, copy) NSString * _Nullable price;
@property (nonatomic, readonly, copy) NSString * _Nullable advertiser;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP8Playwire19PWNativeViewFactory_")
@protocol PWNativeViewFactory
- (UIView * _Nonnull)createAdContentViewWithNativeView:(PWNativeView * _Nonnull)nativeView adContent:(PWNativeViewContent * _Nonnull)adContent SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)callToActionViewWithNativeView:(PWNativeView * _Nonnull)nativeView adContentView:(UIView * _Nonnull)adContentView SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC8Playwire10PWNotifier")
@interface PWNotifier : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PWNotifier * _Nonnull shared;)
+ (PWNotifier * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)startConsoleLogger;
- (void)startConsoleLoggerWithFilter:(BOOL (^ _Nonnull)(NSString * _Nonnull, BOOL, NSDictionary<NSString *, id> * _Nonnull))filter;
- (PWListenerToken * _Nonnull)addListener:(id _Nonnull)listener filter:(BOOL (^ _Nonnull)(NSString * _Nonnull, BOOL, NSDictionary<NSString *, id> * _Nonnull))filter action:(void (^ _Nonnull)(id _Nonnull, NSString * _Nonnull, BOOL, NSDictionary<NSString *, id> * _Nonnull, NSDictionary<NSString *, id> * _Nonnull))action;
- (void)notifyWithEvent:(NSString * _Nonnull)event critical:(BOOL)critical context:(NSDictionary<NSString *, id> * _Nullable)context data:(NSDictionary<NSString *, id> * _Nonnull)data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8Playwire10PWOMConfig")
@interface PWOMConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull partnerName;
@property (nonatomic, readonly, copy) NSString * _Nonnull partnerVersion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8Playwire10PWRewarded")
@interface PWRewarded : PWFullScreenAd
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName delegate:(id <PWFullScreenAdDelegate> _Nullable)delegate;
- (void)showFromViewController:(UIViewController * _Nonnull)viewController;
@end


SWIFT_CLASS("_TtC8Playwire22PWRewardedInterstitial")
@interface PWRewardedInterstitial : PWFullScreenAd
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName delegate:(id <PWFullScreenAdDelegate> _Nullable)delegate;
- (void)showFromViewController:(UIViewController * _Nonnull)viewController;
@end

@class SchainNodeConfig;

SWIFT_CLASS("_TtC8Playwire14PWSchainConfig")
@interface PWSchainConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull ver;
@property (nonatomic, readonly) NSInteger complete;
@property (nonatomic, readonly, copy) NSArray<SchainNodeConfig *> * _Nonnull nodes;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull dictionary;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8Playwire11PWUMPConfig")
@interface PWUMPConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWUMPLocation_Current;)
+ (NSString * _Nonnull)PWUMPLocation_Current SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWUMPLocation_EEA;)
+ (NSString * _Nonnull)PWUMPLocation_EEA SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWUMPLocation_NotEEA;)
+ (NSString * _Nonnull)PWUMPLocation_NotEEA SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable debugDevices;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




SWIFT_PROTOCOL("_TtP8Playwire16PWViewAdDelegate_")
@protocol PWViewAdDelegate
- (void)viewAdDidLoad:(PWViewAd * _Nonnull)ad;
- (void)viewAdDidFailToLoad:(PWViewAd * _Nonnull)ad;
- (void)viewAdWillPresentFullScreenContent:(PWViewAd * _Nonnull)ad;
- (void)viewAdWillDismissFullScreenContent:(PWViewAd * _Nonnull)ad;
- (void)viewAdDidDismissFullScreenContent:(PWViewAd * _Nonnull)ad;
- (void)viewAdDidRecordImpression:(PWViewAd * _Nonnull)ad;
- (void)viewAdDidRecordClick:(PWViewAd * _Nonnull)ad;
@end


SWIFT_CLASS("_TtC8Playwire11PlaywireSDK")
@interface PlaywireSDK : NSObject
@property (nonatomic, readonly, strong) PWAdUnitStoreConfig * _Nullable config;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PlaywireSDK * _Nonnull shared;)
+ (PlaywireSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)initializeWithPublisherId:(NSString * _Nonnull)publisherId appId:(NSString * _Nonnull)appId viewController:(UIViewController * _Nonnull)viewController completionHandler:(void (^ _Nonnull)(void))completionHandler;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSArray<NSString *> *> * _Nonnull adUnitsDictionary;
- (void)setWithType:(Class <PWAdMediator> _Nonnull)type for:(NSString * _Nonnull)mediator;
- (void)configureWithRequest:(GADRequest * _Nonnull)request;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
