// Generated by Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
#ifndef PLAYWIRE_SWIFT_H
#define PLAYWIRE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import GoogleMobileAds;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Playwire",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC8Playwire10PWAdBidder")
@interface PWAdBidder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8Playwire12PWAdMediator")
@interface PWAdMediator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

SWIFT_CLASS("_TtC8Playwire18PWAdMediatorConfig")
@interface PWAdMediatorConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdMediatorType_AdColony;)
+ (NSString * _Nonnull)PWAdMediatorType_AdColony SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdMediatorType_Vungle;)
+ (NSString * _Nonnull)PWAdMediatorType_Vungle SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdMediatorType_Smaato;)
+ (NSString * _Nonnull)PWAdMediatorType_Smaato SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nullable adcolony_appId;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable adcolony_zones;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable vungle_placements;
@property (nonatomic, readonly, copy) NSString * _Nullable vungle_userId;
@property (nonatomic, readonly, copy) NSString * _Nullable smaato_publisherId;
@end


SWIFT_CLASS("_TtC8Playwire16PWAdServerConfig")
@interface PWAdServerConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdServerType_Amazon;)
+ (NSString * _Nonnull)PWAdServerType_Amazon SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdServerType_Prebid;)
+ (NSString * _Nonnull)PWAdServerType_Prebid SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nullable host;
@property (nonatomic, readonly, copy) NSString * _Nullable account;
@end

@class NSNumber;

SWIFT_CLASS("_TtC8Playwire8PWAdSize")
@interface PWAdSize : NSObject
@property (nonatomic, readonly) NSInteger width;
@property (nonatomic, readonly) NSInteger height;
@end

@class PWAdUnitConfig;

SWIFT_CLASS("_TtC8Playwire8PWAdUnit")
@interface PWAdUnit : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdBidStrategyType_Priority;)
+ (NSString * _Nonnull)PWAdBidStrategyType_Priority SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdBidStrategyType_Combined;)
+ (NSString * _Nonnull)PWAdBidStrategyType_Combined SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdMode_Banner;)
+ (NSString * _Nonnull)PWAdMode_Banner SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdMode_Interstitial;)
+ (NSString * _Nonnull)PWAdMode_Interstitial SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWAdMode_Rewarded;)
+ (NSString * _Nonnull)PWAdMode_Rewarded SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSArray<PWAdUnitConfig *> * _Nullable adUnitConfigs;
@property (nonatomic, readonly, copy) NSString * _Nonnull gadUnitId;
@property (nonatomic, readonly, copy) NSArray<PWAdSize *> * _Nullable gadSizes;
@end


SWIFT_CLASS("_TtC8Playwire14PWAdUnitConfig")
@interface PWAdUnitConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull serverConfig;
@property (nonatomic, readonly, copy) NSString * _Nonnull adUnitId;
@property (nonatomic, readonly, copy) NSArray<PWAdSize *> * _Nullable adSizes;
@end

@class PWUMPConfig;
@class PWAppConfig;
@class PWOMConfig;

SWIFT_CLASS("_TtC8Playwire19PWAdUnitStoreConfig")
@interface PWAdUnitStoreConfig : NSObject
@property (nonatomic, readonly, copy) NSArray<PWAdServerConfig *> * _Nullable serverConfigs;
@property (nonatomic, readonly, copy) NSArray<PWAdUnit *> * _Nonnull adUnits;
@property (nonatomic, readonly, copy) NSArray<PWAdMediatorConfig *> * _Nullable mediators;
@property (nonatomic, readonly, strong) PWUMPConfig * _Nullable ump;
@property (nonatomic, readonly, strong) PWAppConfig * _Nullable app;
@property (nonatomic, readonly, strong) PWOMConfig * _Nullable om;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8Playwire11PWAppConfig")
@interface PWAppConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable gamAppId;
@property (nonatomic, readonly, copy) NSString * _Nullable storeUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol PWBannerViewDelegate;
@class NSCoder;

IB_DESIGNABLE
SWIFT_CLASS("_TtC8Playwire12PWBannerView")
@interface PWBannerView : UIView
@property (nonatomic, copy) IBInspectable NSString * _Nullable adUnitName;
@property (nonatomic, weak) id <PWBannerViewDelegate> _Nullable delegate;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName delegate:(id <PWBannerViewDelegate> _Nullable)delegate;
- (void)load;
@property (nonatomic, readonly) BOOL isLoaded;
@end

@class GADBannerView;

@interface PWBannerView (SWIFT_EXTENSION(Playwire)) <GADBannerViewDelegate>
- (void)bannerViewDidReceiveAd:(GADBannerView * _Nonnull)bannerView;
- (void)bannerView:(GADBannerView * _Nonnull)bannerView didFailToReceiveAdWithError:(NSError * _Nonnull)error;
- (void)bannerViewDidRecordImpression:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewbannerViewDidRecordClick:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewWillPresentScreen:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewWillDismissScreen:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewDidDismissScreen:(GADBannerView * _Nonnull)bannerView;
@end


SWIFT_PROTOCOL("_TtP8Playwire20PWBannerViewDelegate_")
@protocol PWBannerViewDelegate
- (void)bannerViewDidReceiveAd:(PWBannerView * _Nonnull)bannerView;
- (void)bannerView:(PWBannerView * _Nonnull)bannerView didFailToReceiveAdWithError:(NSString * _Nonnull)error;
- (void)bannerViewDidRecordImpression:(PWBannerView * _Nonnull)bannerView;
- (void)bannerViewDidRecordClick:(PWBannerView * _Nonnull)bannerView;
- (void)bannerViewWillPresentScreen:(PWBannerView * _Nonnull)bannerView;
- (void)bannerViewWillDismissScreen:(PWBannerView * _Nonnull)bannerView;
- (void)bannerViewDidDismissScreen:(PWBannerView * _Nonnull)bannerView;
@end


SWIFT_CLASS("_TtC8Playwire3PWC")
@interface PWC : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull Version;)
+ (NSString * _Nonnull)Version SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamInit;)
+ (NSString * _Nonnull)EVT_gamInit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamInit_status;)
+ (NSString * _Nonnull)EVT_gamInit_status SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_ump;)
+ (NSString * _Nonnull)EVT_ump SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_ump_result;)
+ (NSString * _Nonnull)EVT_ump_result SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_bidding_index;)
+ (NSString * _Nonnull)EVT_CTX_bidding_index SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_bidding_adUnit;)
+ (NSString * _Nonnull)EVT_CTX_bidding_adUnit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_biddingStart;)
+ (NSString * _Nonnull)EVT_biddingStart SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_biddingStart_timestamp;)
+ (NSString * _Nonnull)EVT_biddingStart_timestamp SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_biddingEnd;)
+ (NSString * _Nonnull)EVT_biddingEnd SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_biddingEnd_timestamp;)
+ (NSString * _Nonnull)EVT_biddingEnd_timestamp SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_biddingEnd_duration;)
+ (NSString * _Nonnull)EVT_biddingEnd_duration SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_adUnit_mode;)
+ (NSString * _Nonnull)EVT_CTX_adUnit_mode SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_adUnit_name;)
+ (NSString * _Nonnull)EVT_CTX_adUnit_name SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_adUnit_gadUnitId;)
+ (NSString * _Nonnull)EVT_CTX_adUnit_gadUnitId SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_requestTimestamp;)
+ (NSString * _Nonnull)EVT_CTX_requestTimestamp SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestSuccess;)
+ (NSString * _Nonnull)EVT_gamRequestSuccess SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestSuccess_response;)
+ (NSString * _Nonnull)EVT_gamRequestSuccess_response SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestSuccess_timestamp;)
+ (NSString * _Nonnull)EVT_gamRequestSuccess_timestamp SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestSuccess_duration;)
+ (NSString * _Nonnull)EVT_gamRequestSuccess_duration SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestFail;)
+ (NSString * _Nonnull)EVT_gamRequestFail SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestFail_error;)
+ (NSString * _Nonnull)EVT_gamRequestFail_error SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestFail_timestamp;)
+ (NSString * _Nonnull)EVT_gamRequestFail_timestamp SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamRequestFail_duration;)
+ (NSString * _Nonnull)EVT_gamRequestFail_duration SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamImpression;)
+ (NSString * _Nonnull)EVT_gamImpression SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_gamImpression_timestamp;)
+ (NSString * _Nonnull)EVT_gamImpression_timestamp SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_configType;)
+ (NSString * _Nonnull)EVT_CTX_configType SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_configType_String;)
+ (NSString * _Nonnull)EVT_CTX_configType_String SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_CTX_configType_Resource;)
+ (NSString * _Nonnull)EVT_CTX_configType_Resource SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_configSuccess;)
+ (NSString * _Nonnull)EVT_configSuccess SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_configSuccess_config;)
+ (NSString * _Nonnull)EVT_configSuccess_config SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_configFail;)
+ (NSString * _Nonnull)EVT_configFail SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_configFail_config;)
+ (NSString * _Nonnull)EVT_configFail_config SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_configFail_resource;)
+ (NSString * _Nonnull)EVT_configFail_resource SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_bannerInitError;)
+ (NSString * _Nonnull)EVT_bannerInitError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_bannerInitError_error;)
+ (NSString * _Nonnull)EVT_bannerInitError_error SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_bannerInitError_error_alreadyInitialized;)
+ (NSString * _Nonnull)EVT_bannerInitError_error_alreadyInitialized SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_bannerInitError_error_noAdUnitName;)
+ (NSString * _Nonnull)EVT_bannerInitError_error_noAdUnitName SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_bannerInitError_error_noAdUnit;)
+ (NSString * _Nonnull)EVT_bannerInitError_error_noAdUnit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_bannerInitError_error_badAdUnit;)
+ (NSString * _Nonnull)EVT_bannerInitError_error_badAdUnit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_bannerInitError_error_noSizes;)
+ (NSString * _Nonnull)EVT_bannerInitError_error_noSizes SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_bannerLoadError;)
+ (NSString * _Nonnull)EVT_bannerLoadError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_bannerLoadError_error;)
+ (NSString * _Nonnull)EVT_bannerLoadError_error SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_bannerLoadError_error_notPrepared;)
+ (NSString * _Nonnull)EVT_bannerLoadError_error_notPrepared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_bannerLoadError_error_notInternalRep;)
+ (NSString * _Nonnull)EVT_bannerLoadError_error_notInternalRep SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_interstitialInitError;)
+ (NSString * _Nonnull)EVT_interstitialInitError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_interstitialInitError_error;)
+ (NSString * _Nonnull)EVT_interstitialInitError_error SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_interstitialInitError_error_noAdUnit;)
+ (NSString * _Nonnull)EVT_interstitialInitError_error_noAdUnit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_interstitialInitError_error_badAdUnit;)
+ (NSString * _Nonnull)EVT_interstitialInitError_error_badAdUnit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_interstitialLoadError;)
+ (NSString * _Nonnull)EVT_interstitialLoadError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_interstitialLoadError_error;)
+ (NSString * _Nonnull)EVT_interstitialLoadError_error SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_interstitialLoadError_error_notPrepared;)
+ (NSString * _Nonnull)EVT_interstitialLoadError_error_notPrepared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_interstitialLoadError_error_notLoaded;)
+ (NSString * _Nonnull)EVT_interstitialLoadError_error_notLoaded SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_interstitialLoadError_error_notInternalRep;)
+ (NSString * _Nonnull)EVT_interstitialLoadError_error_notInternalRep SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_rewardedInitError;)
+ (NSString * _Nonnull)EVT_rewardedInitError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_rewardedInitError_error;)
+ (NSString * _Nonnull)EVT_rewardedInitError_error SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_rewardedInitError_error_noAdUnit;)
+ (NSString * _Nonnull)EVT_rewardedInitError_error_noAdUnit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_rewardedInitError_error_badAdUnit;)
+ (NSString * _Nonnull)EVT_rewardedInitError_error_badAdUnit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_rewardedLoadError;)
+ (NSString * _Nonnull)EVT_rewardedLoadError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_rewardedLoadError_error;)
+ (NSString * _Nonnull)EVT_rewardedLoadError_error SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_rewardedLoadError_error_notPrepared;)
+ (NSString * _Nonnull)EVT_rewardedLoadError_error_notPrepared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_rewardedLoadError_error_notLoaded;)
+ (NSString * _Nonnull)EVT_rewardedLoadError_error_notLoaded SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_rewardedLoadError_error_notInternalRep;)
+ (NSString * _Nonnull)EVT_rewardedLoadError_error_notInternalRep SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_rewardedReward;)
+ (NSString * _Nonnull)EVT_rewardedReward SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_rewardedReward_type;)
+ (NSString * _Nonnull)EVT_rewardedReward_type SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVT_rewardedReward_amount;)
+ (NSString * _Nonnull)EVT_rewardedReward_amount SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP8Playwire18PWConfigFileLoader_")
@protocol PWConfigFileLoader
- (PWAdUnitStoreConfig * _Nonnull)getConfig SWIFT_WARN_UNUSED_RESULT;
@end

@protocol PWInterstitialDelegate;
@class UIViewController;

SWIFT_CLASS("_TtC8Playwire14PWInterstitial")
@interface PWInterstitial : NSObject
@property (nonatomic, weak) id <PWInterstitialDelegate> _Nullable delegate;
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName delegate:(id <PWInterstitialDelegate> _Nullable)delegate OBJC_DESIGNATED_INITIALIZER;
- (void)load;
@property (nonatomic, readonly) BOOL isLoaded;
- (void)showFromViewController:(UIViewController * _Nonnull)viewController;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol GADFullScreenPresentingAd;

@interface PWInterstitial (SWIFT_EXTENSION(Playwire)) <GADFullScreenContentDelegate>
- (void)adDidPresentFullScreenContent:(id <GADFullScreenPresentingAd> _Nonnull)ad;
- (void)adDidDismissFullScreenContent:(id <GADFullScreenPresentingAd> _Nonnull)ad;
- (void)ad:(id <GADFullScreenPresentingAd> _Nonnull)ad didFailToPresentFullScreenContentWithError:(NSError * _Nonnull)error;
- (void)adDidRecordImpression:(id <GADFullScreenPresentingAd> _Nonnull)ad;
- (void)adDidRecordClick:(id <GADFullScreenPresentingAd> _Nonnull)ad;
@end


SWIFT_PROTOCOL("_TtP8Playwire22PWInterstitialDelegate_")
@protocol PWInterstitialDelegate
- (void)interstitialDidReceiveAd:(PWInterstitial * _Nonnull)ad;
- (void)interstitial:(PWInterstitial * _Nonnull)interstitial didFailToReceiveAdWithError:(NSString * _Nonnull)error;
- (void)interstitialDidPresentFullScreenContent:(PWInterstitial * _Nonnull)interstitial;
- (void)interstitialDidDismissFullScreenContent:(PWInterstitial * _Nonnull)interstitial;
- (void)interstitial:(PWInterstitial * _Nonnull)interstitial didFailToPresentFullScreenContentWithError:(NSString * _Nonnull)error;
- (void)interstitialDidRecordImpression:(PWInterstitial * _Nonnull)ad;
- (void)interstitialDidRecordClick:(PWInterstitial * _Nonnull)ad;
@end


SWIFT_CLASS("_TtC8Playwire15PWListenerToken")
@interface PWListenerToken : NSObject
- (void)cancel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8Playwire10PWNotifier")
@interface PWNotifier : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PWNotifier * _Nonnull shared;)
+ (PWNotifier * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (NSInteger)timestamp SWIFT_WARN_UNUSED_RESULT;
- (void)startConsoleLogger;
- (void)startConsoleLoggerWithFilter:(BOOL (^ _Nonnull)(NSString * _Nonnull, BOOL, NSDictionary<NSString *, id> * _Nonnull))filter;
- (PWListenerToken * _Nonnull)addListener:(id _Nonnull)listener filter:(BOOL (^ _Nonnull)(NSString * _Nonnull, BOOL, NSDictionary<NSString *, id> * _Nonnull))filter action:(void (^ _Nonnull)(id _Nonnull, NSString * _Nonnull, BOOL, NSDictionary<NSString *, id> * _Nonnull, NSDictionary<NSString *, id> * _Nonnull))action;
- (void)notifyWithEvent:(NSString * _Nonnull)event critical:(BOOL)critical context:(NSDictionary<NSString *, id> * _Nullable)context data:(NSDictionary<NSString *, id> * _Nonnull)data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8Playwire10PWOMConfig")
@interface PWOMConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull partnerName;
@property (nonatomic, readonly, copy) NSString * _Nonnull partnerVersion;
@end


SWIFT_CLASS("_TtC8Playwire26PWResourceConfigFileLoader")
@interface PWResourceConfigFileLoader : NSObject <PWConfigFileLoader>
- (nonnull instancetype)initWithResource:(NSString * _Nonnull)resource withExtension:(NSString * _Nonnull)ext OBJC_DESIGNATED_INITIALIZER;
- (PWAdUnitStoreConfig * _Nonnull)getConfig SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol PWRewardedDelegate;

SWIFT_CLASS("_TtC8Playwire10PWRewarded")
@interface PWRewarded : NSObject
@property (nonatomic, weak) id <PWRewardedDelegate> _Nullable delegate;
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName delegate:(id <PWRewardedDelegate> _Nullable)delegate OBJC_DESIGNATED_INITIALIZER;
- (void)load;
@property (nonatomic, readonly) BOOL isLoaded;
- (void)showFromViewController:(UIViewController * _Nonnull)viewController;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface PWRewarded (SWIFT_EXTENSION(Playwire)) <GADFullScreenContentDelegate>
- (void)adDidPresentFullScreenContent:(id <GADFullScreenPresentingAd> _Nonnull)ad;
- (void)adDidDismissFullScreenContent:(id <GADFullScreenPresentingAd> _Nonnull)ad;
- (void)ad:(id <GADFullScreenPresentingAd> _Nonnull)ad didFailToPresentFullScreenContentWithError:(NSError * _Nonnull)error;
- (void)adDidRecordImpression:(id <GADFullScreenPresentingAd> _Nonnull)ad;
- (void)adDidRecordClick:(id <GADFullScreenPresentingAd> _Nonnull)ad;
@end


SWIFT_PROTOCOL("_TtP8Playwire18PWRewardedDelegate_")
@protocol PWRewardedDelegate
- (void)rewardedDidLoad:(PWRewarded * _Nonnull)rewarded;
- (void)rewarded:(PWRewarded * _Nonnull)rewarded didFailToLoadWithError:(NSString * _Nonnull)error;
- (void)rewardedDidUserEarn:(PWRewarded * _Nonnull)rewarded type:(NSString * _Nonnull)type amount:(double)amount;
- (void)rewardedDidPresentFullScreenContent:(PWRewarded * _Nonnull)rewarded;
- (void)rewardedDidDismissFullScreenContent:(PWRewarded * _Nonnull)rewarded;
- (void)rewarded:(PWRewarded * _Nonnull)rewarded didFailToPresentFullScreenContentWithError:(NSString * _Nonnull)error;
- (void)rewardedDidRecordImpression:(PWRewarded * _Nonnull)ad;
- (void)rewardedDidRecordClick:(PWRewarded * _Nonnull)ad;
@end


SWIFT_CLASS("_TtC8Playwire24PWStringConfigFileLoader")
@interface PWStringConfigFileLoader : NSObject <PWConfigFileLoader>
- (nonnull instancetype)initWithString:(NSString * _Nonnull)string OBJC_DESIGNATED_INITIALIZER;
- (PWAdUnitStoreConfig * _Nonnull)getConfig SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8Playwire11PWUMPConfig")
@interface PWUMPConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWUMPLocation_Current;)
+ (NSString * _Nonnull)PWUMPLocation_Current SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWUMPLocation_EEA;)
+ (NSString * _Nonnull)PWUMPLocation_EEA SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PWUMPLocation_NotEEA;)
+ (NSString * _Nonnull)PWUMPLocation_NotEEA SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable debugDevices;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class GADRequest;

SWIFT_CLASS("_TtC8Playwire11PlaywireSDK")
@interface PlaywireSDK : NSObject
@property (nonatomic, readonly, strong) PWAdUnitStoreConfig * _Nullable config;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PlaywireSDK * _Nonnull shared;)
+ (PlaywireSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) id <PWConfigFileLoader> _Nonnull configLoader;
- (void)initializeWithViewController:(UIViewController * _Nonnull)viewController completionHandler:(void (^ _Nonnull)(void))completionHandler;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSArray<NSString *> *> * _Nonnull adUnitsDictionary;
- (void)configureWithRequest:(GADRequest * _Nonnull)request;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
